services:
  web:
    image: nginx:alpine
    container_name: portfolio_web
    ports:
      - "3000:80" 
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
